### ISSUE TITLE
flashメッセージの表示の見た目がバラバラになっている。

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#101]
ページによってメッセージの表示位置が異なると、ユーザーがエラーの原因を知りたいときの目線の動かし方がページによって異なり、ユーザーが疲れてしまうと思います。

時間を作って誰かが統一して、後はそれに従うようにしたほうがよいかと思います。
- [x] 表示位置を統一する
- [x] 色の使い方を統一する
- [x] flash[:HOGEHOGE]のHOGEHOGEの部分に利用できる文字列を決める

**Comment by e125762** [comment]
エラーを統一したので閉じます。
