### ISSUE TITLE
思った通りの文字列がビューで表示されていることを確認するテストがない。

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#111]
# 何が問題か
具体的に言うと、Contollerで@applesにバッチリデータが入っていても、ビューで
```
<% @apples.each do |a| %>
<% a.name %>
<% end %>
```
のように、<%= と書くべきところを<%と書いてしまったミスを検知できません。

**Comment by hogehiga** [comment]
ref: <https://trello.com/c/nByyb0zV/69-view>

**Comment by e125762** [comment]
今のところは思った通りの文字列の表示は
実際にページを見て確認することにします。
(開発の中で変更がよくあるので)

**Comment by hogehiga** [comment]
了解しました。
