### ISSUE TITLE
サービスからのエラー通知がチャットに表示される量を減らしたい。

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#112]
GithubのIssueに書くべきかどうか迷いましたが、他に適当な場所が思いつかなかったのでここに書きます。

# 何が問題か
チャットに「ActionController::RoutingError (No route matches [GET] "/apple-touch-icon.png"」というメッセージが出るため、他の重要なエラーが目立たなくなってしまう。

# 解決案
チャットに上記エラーを出さない
- エラー通知サービスで、上記エラーは除外する
- 上記エラーで出ているファイルを設置する。ref: <https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html>

**Comment by e125762** [comment]
上記エラーはfaviconを追加したのでmasterにマージした後は多分大丈夫だと思います。
