### ISSUE TITLE
管理者ページでアーカイブ行きにした追加店は表示されずに別のページに飛んで欲しい。

### ISSUE THREAD

**Issue by Akio-m** [ryupitbros4/itswitter#115]
# 問題点
アーカイブ行きにした追加店は表示されない方がよいです。なぜなら、運営する人がボタンミスを起こしそうです。

![2016-11-02 14 22 24](https://cloud.githubusercontent.com/assets/19320023/19917594/de802018-a107-11e6-97e1-e3d375f0ebff.png)

# 改善案
アーカイブだけのページをつくって、そこにアーカイブ済み店を移動した方がいいです。
あるいは、アーカイブ済みを下に追いやるでもいいです。

とにかく、混在してはダメだと思います。

**Comment by hogehiga** [comment]
確かに。
特にデータが多くなってきたらどんどん間違えちゃいそうですね。

**Comment by hogehiga** [comment]
「アイデア、コメント」に追加しました。

https://trello.com/c/llxEc244/181--

**Comment by hogehiga** [comment]
#158 で対応したのでクローズします。
