### ISSUE TITLE
test/features/visit_all_page_test.rb が、全てのページを辿らない。

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#118]
今はトップページからリンクされているページがテスト対象のため、それ以外のページは表示テストが行われない。

**Comment by Akio-m** [comment]
ログインしないと見れないページへの対応をします。

**Comment by hogehiga** [comment]
お店を削除するために/investigators/:idにDELETEで送信しないといけないのですが、CapybaraでDELETEを送るのが大変っぽいです(参考：<http://qiita.com/katryo/items/61c065795c121566a32d>)。CapybaraのDriverをseleniumかpoltergeistに変えればいけたのですが、いくつか問題があります。

- seleniumだと、ローカルでのテスト中にいきなりブラウザが立ち上がって動く。Travis CIでは設定すれば動く。
- poltergeistだと、各人phantomjsのインストールが必要。Travis CIでは設定すれば動く。

Travis CIでの設定方法→<https://docs.travis-ci.com/user/gui-and-headless-browsers/>

どちらがいいかお返事下さい。

**Comment by hogehiga** [comment]
他にもドライバあるみたいですね。 <https://github.com/jnicklas/capybara#drivers>
Capybara-webkitというのが期待できそうなので試してみてから結果を書きます。

**Comment by hogehiga** [comment]
poltergeistよりも使うのがめんどくさそうなので(参考：<https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit>)やはり上の2つどちらか選んでもらえないでしょうか(rack_testは無しでお願いしたいです……)。

**Comment by hogehiga** [comment]
どちらでもできるようにしました。デフォルトではpoltergeistにしてあります。
理由は、授業用のvagrant仮想マシンでもpoltergeistでテスト実行できたからです
授業用のvagrant仮想マシンでphantomjsを利用してテストをする手順はWikiに書きました。 <https://github.com/ryupitbros4/itswitter/wiki/Softwere-Test#%E6%8E%88%E6%A5%AD%E3%81%A7%E9%85%8D%E5%B8%83%E3%81%95%E3%82%8C%E3%81%9F%E4%BB%AE%E6%83%B3%E3%83%9E%E3%82%B7%E3%83%B3%E3%81%A7%E3%81%AEsuitell%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E8%A1%8C%E6%96%B9%E6%B3%95>

**Comment by hogehiga** [comment]
おそらくpoltergeistにしたことにより、全ページを辿らなくなりました。原因は、 <https://github.com/ryupitbros4/itswitter/blob/master/test/features/visit_all_page_test.rb#L33>で、a[:href]がhttp://127.0.0.1:${PORT}/restaurants/index のような形式になっていることです。試しに直してみます。

**Comment by hogehiga** [comment]
あとは、
- ログインしているときにはログアウト
- ログアウトしているときにはログイン
をそれぞれクリックしないようにしないといけないので、それもやってみます。

**Comment by hogehiga** [comment]
#168 がマージされたのでcloseします。
