### ISSUE TITLE
お店の状況を伝える画面でログインをクリックすると、エラー画面になる。

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#122]
# 再現方法
1. http://localhost:3000/ にアクセスする
1. 「お店の状況を伝える」をクリックする
1. 「ログイン」をクリックする

# 期待される結果
(Twitterの)ログイン画面が表示される

# 実際の結果
「No route matches [GET] "/restaurants/auth/twitter"」というエラー画面が表示される

**Comment by hogehiga** [comment]
78b03b5058d0e3e87e932cd06f45570b2257d8e4 で確認しました。

**Comment by itomasameteo** [comment]
解決したと思うんで閉じます
