### ISSUE TITLE
明らかに閉店している時間にも関わらず、CLOSEにならない。

### ISSUE THREAD

**Issue by Akio-m** [ryupitbros4/itswitter#152]
# 症状
深夜2時に訪問したページの状況です。
![2016-11-12 2 06 24](https://cloud.githubusercontent.com/assets/19320023/20223359/b2c6bc62-a87c-11e6-87f4-96506877a302.png)

# 改善
* 定休日や開店時間を登録時に追加しておく。(直打ち、APIから取得など)
* 現在時間と比較して開店時間とマッチしていなければCLOSEにする。

**Comment by hogehiga** [comment]
最終更新時の時点での混雑度なので、別にそのままでいいと思うのですが……

**Comment by Akio-m** [comment]
少なくとも、閉店かどうかは知りたいですね。
例えば鳥玉は21時には閉まっちゃうので、21時過ぎに空いている情報を得て行っても、がっかり感がひどいですね。

**Comment by e125743** [comment]
commentsテーブルは更新しないで、トップページの表示だけ更新するみたいな感じで良いですよね？これだったら、　
```
  def crowdedness
    c = Comment.where(restaurant_id: self.id).order(updated_at: :desc).limit(1).first
    #トップページの表示だけを変える。commentsテーブルのcrowdednessは変えない。
    return c.crowdedness if c and (Time.zone.now - c.updated_at).to_i <= 3600
    return 6
  end
```
↑この辺弄れば行けそう。

**Comment by hogehiga** [comment]
設定する機能としては #170 のマージにより取り込まれました。
あとは実際に設定する作業が残ってます。

**Comment by e125743** [comment]
本番環境で公開している店に営業時間を入力しました。
　
ただし、曜日によって営業時間が変わるお店は、営業時間を入力していません。
今の実装では、曜日毎の営業時間まで考慮できていないからです。

**Comment by e125743** [comment]
営業時間を入力していないお店は、

[あがり](https://tabelog.com/okinawa/A4703/A470404/47001004/)
[ポケットマーニー　宜野湾店](https://tabelog.com/okinawa/A4703/A470404/47007777/)
[食堂インド　牧志店](https://tabelog.com/okinawa/A4701/A470101/47000190/)
[もとなり　銘苅店](https://tabelog.com/okinawa/A4701/A470103/47007527/)

の４軒です。

**Comment by e125762** [comment]
おっけー
大内さんissueを閉じてください。
