### ISSUE TITLE
店名の検索で使用している like で % とか _ を エスケープしていない

### ISSUE THREAD

**Issue by innparusu95** [ryupitbros4/itswitter#58]
## 症状
restaurants_controller の search で使用している like で 

`%` や `_` をエスケープしてないため, 検索すると店舗全てが表示される.

``` ruby
def search
  @searched = Restaurant.where("name like '%" + params[:name] + "%'" + "or hurigana like '%" + params[:name] + "%'") # ここ
.....
```

![bug](https://cloud.githubusercontent.com/assets/1710115/19443810/f58079c0-94c8-11e6-8fc8-858b32e26de1.gif)

## 対処法
ググった感じ

http://easyramble.com/escape-like-on-rails-active-record.html

とか, ワイルドカードを `String#gsub` で エスケープするらしい(Rails のライブラリであるかもしれない)

**Comment by hogehiga** [comment]
Issue報告ありがとうございます。

**Comment by hogehiga** [comment]
#60 で対応したのでcloseします。
