### ISSUE TITLE
以前表示されたエラーメッセージが一瞬表示される

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#69]
すぐに消えるんですが、ちょっと気持ち悪いです。
# 再現手順
- https://suitell.herokuapp.com/restaurants/report にアクセスする
- 伝えるをクリックする(そうすると、店名を選択して下さいという旨のエラーメッセージ(Aとよぶ)が出る)
- 左上のいつくる？のロゴをクリックする
- ページ下部のtestをクリックする
# 実際の結果
- 一瞬だけAが表示され、すぐに消える
# 期待される結果
- Aが表示されない

**Comment by Akio-m** [comment]
この問題、ご意見のページにも起こります。

**Comment by hogehiga** [comment]
turbolinksを無効にしたら再現しなくなりました。
