### ISSUE TITLE
申請ページにアクセスできない。

### ISSUE THREAD

**Issue by Akio-m** [ryupitbros4/itswitter#73]
https://suitell.herokuapp.com/demands/index にアクセスできません。
多分データベースだと思いますが。

**Comment by itomasameteo** [comment]
権限がある人がheroku rake db:migrateすれば治ると思います
あとherokuのページが変わったせいか権限がなくなってます

**Comment by hogehiga** [comment]
アクセスできることを確認したのでクローズします。
