### ISSUE TITLE
トップ画面で混雑度「記録なし」が混雑度「空いてる」よりも上に来る

### ISSUE THREAD

**Issue by hogehiga** [ryupitbros4/itswitter#84]
ちょっと再現手順がわからないのですが、報告です。
ごはんを早く食べたい人向けのサービスなので、不確かな「記録なし」よりは、「空いてる」が上にある方がいいと思います。

![2016-10-22 21 18 04](https://cloud.githubusercontent.com/assets/6975731/19619246/617d2d76-989d-11e6-9543-8c3afd1c0a84.png)

**Comment by Akio-m** [comment]
改善しました。
